spring:
    application:
        name: rest-with-spring-curso
    datasource:
         driver-class-name: org.postgresql.Driver
         url: jdbc:postgresql://localhost:5432/CursoLeandro
         username: postgres
         password: 123456789
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
        open-in-view: false

